# Generated by Django 4.2.5 on 2023-10-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'ordering': ['id'], 'verbose_name': 'linea pedido', 'verbose_name_plural': 'lineas pedidos'},
        ),
        migrations.AlterModelTable(
            name='lineapedido',
            table='lineapedidos',
        ),
    ]
